In [83]:
import torch
import numpy as np

a = [[229.4433], [259.0966], [235.3389], [222.0915], [80.1688], [194.6028],
     [350.4031], [138.9966], [333.5420], [89.3357], [313.5604], [288.6507],
     [65.6733], [173.1181], [244.5383], [261.0913]]

b = [[29.4433], [59.0966], [135.3389], [182.0915], [180.4211], [294.6028],
     [50.4031], [338.9966], [300.5420], [289.3357], [13.5604], [88.6507],
     [165.6733], [273.1181], [344.5383], [161.0913]]

# 创建一个形状为(2, 16)的张量
tensor = torch.Tensor([a, b])

print()
print(tensor)
print()
tensor[0, :]


tensor([[[229.4433],
         [259.0966],
         [235.3389],
         [222.0915],
         [ 80.1688],
         [194.6028],
         [350.4031],
         [138.9966],
         [333.5420],
         [ 89.3357],
         [313.5604],
         [288.6507],
         [ 65.6733],
         [173.1181],
         [244.5383],
         [261.0913]],

        [[ 29.4433],
         [ 59.0966],
         [135.3389],
         [182.0915],
         [180.4211],
         [294.6028],
         [ 50.4031],
         [338.9966],
         [300.5420],
         [289.3357],
         [ 13.5604],
         [ 88.6507],
         [165.6733],
         [273.1181],
         [344.5383],
         [161.0913]]])



tensor([[229.4433],
        [259.0966],
        [235.3389],
        [222.0915],
        [ 80.1688],
        [194.6028],
        [350.4031],
        [138.9966],
        [333.5420],
        [ 89.3357],
        [313.5604],
        [288.6507],
        [ 65.6733],
        [173.1181],
        [244.5383],
        [261.0913]])

In [85]:
abs(80.1688 - 313.5604)

233.3916

In [86]:
# 计算差值
diff = tensor[1, :] - tensor[0, :]
diff

tensor([[-200.0000],
        [-200.0000],
        [-100.0000],
        [ -40.0000],
        [ 100.2523],
        [ 100.0000],
        [-300.0000],
        [ 200.0000],
        [ -33.0000],
        [ 200.0000],
        [-300.0000],
        [-200.0000],
        [ 100.0000],
        [ 100.0000],
        [ 100.0000],
        [-100.0000]])

In [79]:
len(a)

16

In [78]:
len(tensor)

2

In [87]:
mse = sum((tensor[1, :] - tensor[0, :])**2)/len(a)
mse

tensor([28296.2207])

In [26]:
tensor[1, :][diff > 180]

tensor([ 29.4433,  59.0966,  50.4031, 338.9966, 289.3357,  13.5604,  88.6507])

In [24]:
tensor[1, :][(diff > 180) & (tensor[1, :] > 180)]

tensor([338.9966, 289.3357])

In [18]:
diff = abs(tensor[1, :] - tensor[0, :])

diff[diff > 180 & (tensor[1, :] > 180)] = 360 + tensor[1, :] + tensor[0, :]

tensor([[200.0000],
        [200.0000],
        [100.0000],
        [ 40.0000],
        [100.2523],
        [100.0000],
        [300.0000],
        [200.0000],
        [ 33.0000],
        [200.0000],
        [300.0000],
        [200.0000],
        [100.0000],
        [100.0000],
        [100.0000],
        [100.0000]])

In [75]:
mask = (abs(tensor[1, :] - tensor[0, :]) > 180)
mask

tensor([[ True],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [False]])

In [70]:
mask1 = tensor[1, :] > tensor[0, :]
mask1

tensor([[False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [False],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [False]])

In [76]:
theta_diff = tensor[1, :] - tensor[0, :]
theta_diff

tensor([[-200.0000],
        [-200.0000],
        [-100.0000],
        [ -40.0000],
        [ 100.2523],
        [ 100.0000],
        [-300.0000],
        [ 200.0000],
        [ -33.0000],
        [ 200.0000],
        [-300.0000],
        [-200.0000],
        [ 100.0000],
        [ 100.0000],
        [ 100.0000],
        [-100.0000]])

In [77]:
theta_diff[mask] = 360 - abs(tensor[1, :][mask]  -  tensor[0, :][mask])
theta_diff

tensor([[ 160.0000],
        [ 160.0000],
        [-100.0000],
        [ -40.0000],
        [ 100.2523],
        [ 100.0000],
        [  60.0000],
        [ 160.0000],
        [ -33.0000],
        [ 160.0000],
        [  60.0000],
        [ 160.0000],
        [ 100.0000],
        [ 100.0000],
        [ 100.0000],
        [-100.0000]])

In [64]:
# 这是个需要360 - y(大) + x 的 mask

mask0 = (abs(tensor[1, :] - tensor[0, :]) > 180) & (tensor[0, :] > tensor[1, :])
mask1 = (abs(tensor[1, :] - tensor[0, :]) > 180) & (tensor[1, :] > tensor[0, :])

tensor[0, :][mask0] *= -1
tensor[1, :][mask1] *= -1
tensor

tensor([[ True],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [False]])

In [58]:
# 选出 y - x 大于180°且 x 大于 180 的值设为负数

mask = (abs(tensor[1, :] - tensor[0, :]) > 180) & (tensor[0, :] > tensor[1, :]) & (tensor[0, :] > tensor[1, :])
tensor[0, :][mask] *= -1

tensor[0, :]

tensor([[-229.4433],
        [-259.0966],
        [ 235.3389],
        [ 222.0915],
        [  80.1688],
        [ 194.6028],
        [-350.4031],
        [ 138.9966],
        [ 333.5420],
        [  89.3357],
        [-313.5604],
        [-288.6507],
        [  65.6733],
        [ 173.1181],
        [ 244.5383],
        [ 261.0913]])

In [43]:
B = - tensor[1, :]
B

tensor([[ -29.4433],
        [ -59.0966],
        [-135.3389],
        [-182.0915],
        [-180.4211],
        [-294.6028],
        [ -50.4031],
        [-338.9966],
        [-300.5420],
        [-289.3357],
        [ -13.5604],
        [ -88.6507],
        [-165.6733],
        [-273.1181],
        [-344.5383],
        [-161.0913]])

In [ ]:
diff[diff > 180 & (tensor[1, :] > 180)] = 360 - tensor[1, :][(diff > 180) & (tensor[1, :] > 180)] + tensor[0, :][(diff > 180) & (tensor[1, :] < 180)]
diff[diff > 180 & (tensor[0, :] > 180)] = 360 - tensor[0, :][(diff > 180) & (tensor[1, :] > 180)] + tensor[0, :][(diff > 180) & (tensor[1, :] < 180)]

In [13]:
tensor[1, :][diff > 180]

tensor([ 29.4433,  59.0966,  50.4031, 338.9966, 289.3357,  13.5604,  88.6507])

In [ ]:
# 处理差值大于180°的情况
diff[diff > 180] = 360 - tensor[1, :][diff > 180] + tensor[0, :][diff > 180]

# 输出结果
print(diff)

In [ ]:
import torch

# 创建一个形状为(2, 16)的张量
tensor = torch.Tensor([[x1, x2, ..., x16],
                       [y1, y2, ..., y16]])

# 计算差值
diff = y - x

# 处理差值大于180°的情况
diff[diff > 180] = 360 - y[diff > 180] + x[diff > 180]

# 输出结果
print(diff)