In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [23]:
# 4,4,5 ——> 
np_3 = np.random.randint(0, 10, (2, 3, 2))
np_3.shape
np_3

array([[[5, 8],
        [5, 4],
        [0, 7]],

       [[1, 6],
        [9, 5],
        [3, 1]]])

In [24]:
B = np.reshape(np_3,(-1,2))
print(B)
B.shape

[[5 8]
 [5 4]
 [0 7]
 [1 6]
 [9 5]
 [3 1]]


(6, 2)

In [27]:
B[:, 0]

array([5, 5, 0, 1, 9, 3])

In [29]:
np.linspace(0, len(B[:, 0]), len(B[:, 0]))

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [28]:
np.arange(B[:, 0])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()