In [85]:
import torch
import torch.nn.functional as Fun
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import learning_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn import metrics
import datetime
from pandas.plotting import radviz
import argparse, os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc
import joblib
from itertools import cycle
from sklearn import datasets

In [86]:
dataset = pd.read_excel('E:\\File_cache\\feiq\\Recv Files\\data_9_120.xlsx')
dataset

合加速度    对数合加速度      均方根值    对数均方根值       峰峰值     对数峰峰值       标准差  \
0    0.000030 -2.851460  0.014771 -2.728709  0.014208 -2.756784  0.005752   
1    0.000051 -2.388829  0.016548 -2.248595  0.017070 -2.196049  0.006928   
2    0.000035 -2.277593  0.017278 -2.156877  0.017223 -2.174182  0.006986   
3    0.000053 -2.285369  0.016774 -2.167150  0.016958 -2.165231  0.006879   
4    0.000047 -2.428037  0.015901 -2.298972  0.016120 -2.287763  0.006542   
..        ...       ...       ...       ...       ...       ...       ...   
115  0.000031 -2.816360  0.014121 -2.703158  0.013613 -2.721710  0.005510   
116  0.000036 -2.817512  0.014209 -2.691561  0.013765 -2.690475  0.005571   
117  0.000045 -2.869202  0.014064 -2.741503  0.013537 -2.771172  0.005480   
118  0.000041 -2.710718  0.014377 -2.588689  0.014088 -2.591960  0.005706   
119  0.000036 -2.845144  0.014062 -2.726375  0.013581 -2.736607  0.005498   

        对数标准差      频域主峰  标签 Unnamed: 10  
0   -3.145751  0.017250   0         无震颤  
1   -2.584288  0.016813   0         无震颤  
2   -2.563832  0.016013   0         无震颤  
3   -2.555175  0.016168   0         无震颤  
4   -2.677084  0.016154   0         无震颤  
..        ...       ...  ..         ...  
115 -3.111796  0.016226   0         无震颤  
116 -3.080044  0.016181   0         无震颤  
117 -3.160949  0.016256   0         无震颤  
118 -2.981536  0.015847   0         无震颤  
119 -3.126473  0.016457   0         无震颤  

[120 rows x 11 columns]

In [87]:
data = dataset.iloc[:, :9].values
iris_type = dataset.iloc[:, -2].values
print(data.shape)
print(iris_type.shape)
# (150, 4)
# (150,)

(120, 9)
(120,)


In [88]:
input = torch.FloatTensor(data)
print(input.shape)
label = torch.LongTensor(iris_type)
print(label.shape)

torch.Size([120, 9])
torch.Size([120])


In [89]:
X_train, X_test, y_train, y_test = train_test_split(input, label, train_size=0.7)

In [90]:
import torch.nn.functional as Fun
# 定义BP神经网络
class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)
        self.out = torch.nn.Linear(n_hidden, n_output)
        
    def forward(self,x):
        x = Fun.relu(self.hidden(x))
        x = self.out(x)
        return x

In [91]:
net = Net(n_feature=9, n_hidden=1000, n_output=3)
optimizer = torch.optim.SGD(net.parameters(), lr=0.0001)
# SGD:随机梯度下降法
loss_func = torch.nn.CrossEntropyLoss()
# 设定损失函数

In [96]:
lis = []
for times in range(10):
    X_train, X_test, y_train, y_test = train_test_split(input, label, train_size=0.7)
    for i in range(10000):
        out = net(X_train)
        loss = loss_func(out, y_train)
        # 输出与label对比
        optimizer.zero_grad()
        # 初始化
        loss.backward()
        optimizer.step()
    
    
    out = net(X_test)
    # out是一个计算矩阵
    prediction = torch.max(out, 1)[1]

    # 实际y输出数据
    target_y = y_test.data.numpy()
    print(target_y)
    pred_y = prediction.numpy()
    # 预测y输出数列
    print(pred_y)
    # 计算准确率——自己写的
    L = pred_y.shape[0]
    flag = 0
    for i in range(L):
        if pred_y[i] == target_y[i]:
            flag += 1
    print("bp准确率为：", flag/L)
    lis.append(flag/L)
sum = 0
for i in lis:
    sum = sum + i
print(sum/len(lis))

[1 1 2 2 0 2 1 1 1 0 0 1 0 0 1 2 1 2 1 1 0 1 0 1 1 1 2 1 0 1 1 1 2 0 2 0]
[1 1 2 2 0 2 1 1 0 0 0 0 0 0 0 1 1 2 1 1 0 1 0 1 1 1 2 2 0 1 1 2 2 0 2 0]
bp准确率为： 0.8333333333333334
[1 2 1 1 2 2 1 1 1 1 0 2 0 0 2 1 1 2 1 1 0 0 2 1 1 2 0 2 0 2 0 2 0 2 1 0]
[1 2 1 1 2 2 0 1 1 0 0 2 0 0 2 1 2 1 1 1 0 0 2 1 1 1 0 2 0 2 0 2 0 2 1 0]
bp准确率为： 0.8611111111111112
[0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 2 2 2 0 0 1 1 0 0 0 1 0 0 2 2 1 1 1 0 0 1]
[0 0 0 0 1 0 0 1 1 1 1 1 0 1 2 1 2 2 0 0 1 1 0 0 0 1 0 0 2 2 1 1 1 0 0 0]
bp准确率为： 0.9166666666666666
[1 1 1 0 2 1 0 0 2 2 2 2 1 2 1 0 1 1 1 2 1 1 2 0 0 2 2 1 1 2 0 2 2 2 0 1]
[2 1 1 0 2 1 0 0 2 2 2 2 1 2 1 0 1 1 1 2 1 1 2 0 0 2 2 1 1 2 0 2 2 2 0 1]
bp准确率为： 0.9722222222222222
[2 1 2 1 2 0 0 2 2 1 2 0 2 0 1 1 0 1 1 0 0 0 0 1 2 0 2 0 0 1 2 1 1 2 1 1]
[2 1 2 1 2 0 0 2 2 0 2 0 2 0 1 1 0 0 1 0 0 0 0 1 2 0 1 0 0 1 2 1 1 2 2 1]
bp准确率为： 0.8888888888888888
[2 0 0 0 0 0 2 0 1 2 1 1 0 2 2 2 1 2 1 2 1 0 2 0 0 1 2 2 1 2 1 2 0 1 1 2]
[2 0 0 0 0 0 2 0 1 2 1 2 0 2 2 1 1 2 0 2 1 0 1 0 0 

In [94]:
out = net(X_test)
# out是一个计算矩阵
prediction = torch.max(out, 1)[1]

# 实际y输出数据
target_y = y_test.data.numpy()
print(target_y)
pred_y = prediction.numpy()
# 预测y输出数列
print(pred_y)

[2 2 1 0 1 2 0 0 0 1 2 1 0 1 2 0 2 0 1 1 0 1 1 0 1 0 1 0 1 1 2 2 2 2 0 2]
[2 2 1 0 1 2 0 0 0 1 2 0 0 1 2 0 2 0 2 1 0 0 1 0 1 0 1 0 1 1 2 2 2 2 0 1]


In [95]:
# 计算准确率——自己写的
L = pred_y.shape[0]
flag = 0
for i in range(L):
    if pred_y[i] == target_y[i]:
        flag += 1
print("bp准确率为：", flag/L)

bp准确率为： 0.8888888888888888
